// Generated by Karakum - do not modify it manually!

@file:JsModule("dev-shibasis-reaktor-navigation-karakum/karakum")

package dev.shibasis.reaktor.navigation.karakum

external class Greeter {
constructor (greeting: String)
fun greet(name: String): String
}
