// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Color } from './monster/color.js';
export { Equipment } from './monster/equipment.js';
export { Monster, MonsterT } from './monster/monster.js';
export { Vec3, Vec3T } from './monster/vec3.js';
export { Weapon, WeaponT } from './monster/weapon.js';
