@file:OptIn(ExperimentalUnsignedTypes::class)

package dev.shibasis.reaktor.flexbuffer.core

import dev.shibasis.reaktor.flexbuffer.flatbuffers.FlexBuffersBuilder
import dev.shibasis.reaktor.flexbuffer.flatbuffers.Reference
import kotlin.reflect.KClass

/**
 * Direct encode/decode interface that bypasses kotlinx.serialization's
 * AbstractEncoder/AbstractDecoder virtual dispatch entirely.
 *
 * Implementations call FlexBuffersBuilder methods directly — no per-field
 * virtual dispatch, no descriptor lookup, no structure stack. This matches
 * the "raw builder" performance tier.
 *
 * Fields MUST be written in alphabetical order so endMap()'s TimSort
 * operates in O(n) (already-sorted detection) rather than O(n log n).
 *
 * Generated by KSP for @Serializable classes, or implemented manually
 * for performance-critical types.
 */
interface FlexCoder<T> {
    fun encode(builder: FlexBuffersBuilder, value: T, key: String? = null)
    fun decode(ref: Reference): T
}

/**
 * Registry for FlexCoder instances. Checked by FlexBuffers.encode/decode
 * before falling through to the kotlinx.serialization path.
 *
 * Thread-safe for reads after initialization (typical usage: register at startup).
 * Registration during encoding is safe but not recommended.
 */
object FlexCoderRegistry {
    @PublishedApi
    internal val coders = HashMap<KClass<*>, FlexCoder<*>>(32)

    // Secondary index by kotlinx.serialization serial name.
    // Enables FlexCoder acceleration for the serializer-based API
    // (FlexBuffers.encode(serializer, value)) without needing reified T.
    @PublishedApi
    internal val codersBySerialName = HashMap<String, FlexCoder<*>>(32)

    inline fun <reified T : Any> register(coder: FlexCoder<T>) {
        coders[T::class] = coder
    }

    fun <T : Any> register(klass: KClass<T>, coder: FlexCoder<T>) {
        coders[klass] = coder
    }

    /**
     * Register a coder with its serial name for serializer-based API acceleration.
     * Call this alongside the standard register() to enable acceleration of
     * FlexBuffers.encode(serializer<T>(), value) without reified T.
     */
    fun <T : Any> registerBySerialName(serialName: String, coder: FlexCoder<T>) {
        codersBySerialName[serialName] = coder
    }

    @Suppress("UNCHECKED_CAST")
    fun <T : Any> get(klass: KClass<T>): FlexCoder<T>? {
        return coders[klass] as? FlexCoder<T>
    }

    @Suppress("UNCHECKED_CAST")
    inline fun <reified T : Any> get(): FlexCoder<T>? {
        return coders[T::class] as? FlexCoder<T>
    }

    /**
     * Look up a FlexCoder by kotlinx.serialization serial name.
     * Returns null if no coder is registered for this serial name.
     */
    @Suppress("UNCHECKED_CAST")
    fun <T> getBySerialName(serialName: String): FlexCoder<T>? {
        return codersBySerialName[serialName] as? FlexCoder<T>
    }

    fun clear() {
        coders.clear()
        codersBySerialName.clear()
    }
}
