POST  https://mehmaan-post.shibasispatnaik.workers.dev/rafale.jpg
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "field1": "example",
  "field2": 42
}

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="testFile.jpg"
Content-Type: image/jpeg

< ./testFile.jpg
--WebAppBoundary--
